name: notes_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  get_cli: ^1.8.0
  cupertino_icons: ^1.0.6
  get: 4.6.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.17.0
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

